//! Generate the SOP syntax-reference snippets for the mdBook from the
//! canonical catalogs in `zeroclaw-runtime`: the step-bullet catalog
//! (`sop::step_bullets`) and the condition-operator catalog
//! (`sop::condition::ConditionOp`). The catalogs are the single source of
//! truth; the docs render whatever they carry so a parser or evaluator change
//! never drifts the rendered reference.

use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

use zeroclaw_runtime::sop::condition::ConditionOp;
use zeroclaw_runtime::sop::step_bullets;

const SNIPPET_DIR: &str = "docs/book/src/_snippets";

const HEADER: &str = "<!--\n  GENERATED by `cargo mdbook` from the canonical SOP catalogs in\n  crates/zeroclaw-runtime/src/sop/ (step_bullets.rs, condition.rs).\n  Derived + gitignored: do not edit, do not commit. Regenerated on\n  every docs build.\n-->\n\n";

pub fn run(root: &Path) -> Result<()> {
    let dir = root.join(SNIPPET_DIR);
    std::fs::write(dir.join("sop-step-bullets.md"), render_step_bullets())?;
    std::fs::write(
        dir.join("sop-condition-operators.md"),
        render_condition_operators(),
    )?;
    eprintln!("==> Generated SOP syntax snippets from runtime catalogs");
    Ok(())
}

fn render_step_bullets() -> String {
    let mut out = String::from(HEADER);
    for spec in step_bullets::catalog() {
        let _ = write!(out, "- `- {}:`", spec.token);
        if !spec.aliases.is_empty() {
            let aliases: Vec<String> = spec.aliases.iter().map(|a| format!("`- {a}:`")).collect();
            let _ = write!(out, " (also {})", aliases.join(", "));
        }
        let _ = writeln!(out, " {}", spec.description);
    }
    out
}

fn render_condition_operators() -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "A comparison uses one operator, matched longest-token-first so `>=` \
         is never read as `>`:\n\n| Operator | Meaning |\n|---|---|\n",
    );
    for spec in ConditionOp::catalog() {
        let _ = writeln!(out, "| `{}` | {} |", spec.token, spec.label);
    }
    out
}
